# Project information
site_name: UCloud Guides
site_author: CLAAUDIA, ITS, Aalborg University
site_description: Guides for UCloud.

# Copyright
copyright: Copyright &copy; 2024 CLAAUDIA

nav:
  - Home: index.md
  - Getting started:
    - Before you begin: getting-started/before-you-begin.md
  - Help & resources:
    - Support: help-and-resources/support.md
    - Guidelines: help-and-resources/guidelines.md
    - Known issues:  help-and-resources/known-issues.md
    - Glossery:  help-and-resources/glossery.md
    
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.annotate

  logo: assets/img/aau-logo-512x512.png
  favicon: assets/favicon.ico

  font:
    text: barlow
 
  language: en

  icon:
    annotation: material/plus-circle

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/conditional.js

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/claaudia/
      name: Claaudia on LinkedIn

    - icon: fontawesome/solid/globe
      link: https://www.researcher.aau.dk/contact/claaudia
